# Generated by Django 5.0.6 on 2024-07-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_app', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
